name: riskcopilot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - pyarrow
  - openai
  - langchain
  - tqdm
  - requests
  - beautifulsoup4
  - ipykernel
  - jupyterlab
  - pip
  - pip:
      - python-dotenv  # for .env file